err_open: "&4Данное меню могут открывать только игроки" #message for console
start_fight: "&fВы начали поединок с &e%player% &f(&6%kit%&f)"
quantity_arenas: 20 #max 20
#if you want more arenas,
#you can just add them to the cfg,
#you only need to copy the old structure

#name menu
Adkit: "&aАдекватные киты"
PMkit: "&eМенее адекватные киты"
PizdecKit: "&cНу тут вообще пиздец"

#other
select_false: "&cВы уже находитесь в выбранном меню"
select_menu: "&aВы выбрали %BTN_Menu%"

#description kits
crystal_kit:
  - "&fСтандартный кит для cpvp,"
  - "&fкоторый имеет только &dкристаллы"

shield_kit:
  - "&fСтандартный кит для пвп"
  - "&fна &6щитах. &b(щиты нерушимые)"

diamond_kit:
  - "&fКит с алмазной бронёй"
  - "&7ничо особенного"

nether_kit:
  - "&fКит с незеритовой бронёй"
  - "&7ничо особенного"

ender_kit:
  - "&fКит, где дохуя пёрок"
  - "&7Можешь хоть в жопу засунуть"
  - "&7Они всё равно не закончатся"

elytra_kit:
  - "&fСтандартный кит на элитрах"
  - "&bТак же имеется нагрудник"

uhc_kit:
  - "&fСтандартный UHC кит"
  - "&7Для истинных анархистов"

apple_kit:
  - "&fНезер + стак геплов"
  - "&7Приятного аппетита"

anchor_kit:
  - "&fЭто уже для настоящих мужчин"
  - "&7Только истинные анархисты выберут"
  - "&7данный кит"

totem_kit:
  - "&fБля, просто попробуй сдохнуть"
  - "&7Над тобой будет угарать пол "
  - "&b            татарстана"

  #менее адекватные

fight_pig:
  - "&fТут вы верхом на свинье сражаетесь"
  - "&fимеея в арсенале лук и меч"

water_kit:
  - "&9Тут незер кит, где вы сражаетесь"
  - "&9под водой &d(я не ебу как придумал это)"

sumo_kit:
  - "&fОбычное сумо"
  - "&d     >ω< "

crossbow_kit:
  - "&fСтреляйте фейерверками в своего "
  - "&fпротивника. Заставьте его обосраться"

sphere_kit:
  - "&fВ данном ките у вас есть несколько"
  - "&dсфер &fна выбор. Подбери лучшую "
  - "&fкомбинацию для &cубийства!"

trolley_tnt:
  - "&fВзорви противника вагоном с TNT!"
  - "&fДля поджога нужен арбалет и огниво"
  - "&Ловкость рук и ничего больше!"

  #не адекватные

coordinate:
  arena_1:
    players: false
    player1_coordinates:
      - 316 #x
      - 64  #y
      - 327 #z
    player2_coordinates:
      - 294 #x (пример: +34 по X)
      - 64  #y
      - 327 #z
  arena_2:
    players: false
    player1_coordinates:
      - 100 #x
      - 0   #y
      - 51  #z
    player2_coordinates:
      - 150 #x (+50)
      - 0   #y
      - 51  #z
  arena_3:
    players: false
    player1_coordinates:
      - 100 #x
      - 0   #y
      - 51  #z
    player2_coordinates:
      - 150 #x (+50)
      - 0   #y
      - 51  #z
  # ... (аналогично для остальных арен)
  arena_20:
    players: false
    player1_coordinates:
      - 100 #x
      - 0   #y
      - 51  #z
    player2_coordinates:
      - 150 #x (+50)
      - 0   #y
      - 51  #z